# Generated by Django 2.2.6 on 2020-01-21 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdetails',
            name='today_date',
            field=models.TimeField(default=datetime.datetime(2020, 1, 21, 12, 9, 24, 347612, tzinfo=utc)),
        ),
    ]
