# Generated by Django 2.2.6 on 2020-01-21 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20200121_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdetails',
            name='today_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
